# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# (MIT License)

# Read in the private key from k8s
- name: Read in CSM Private key for passwordless SSH
  csm_read_secret:
    name: "{{ csm_private_key_secret }}"
    namespace: "{{ csm_key_namespace }}"
    key: "value"
  register: csm_private_key
  no_log: true
  run_once: true
  delegate_to: localhost

# Write the private key to disk
- name: Write private keyfile to disk with appropriate permissions
  lineinfile:
    create: true
    line: "{{ csm_private_key['response'] }}"
    state: present
    path: /root/.ssh/csm-ecdsa
    mode: '600'
  no_log: true

# Obtain the public half of the key as well
- name: Obtain the public half of the keypair from k8s configmap
  csm_read_configmap:
    name: "{{ csm_public_key_configmap }}"
    namespace: "{{ csm_key_namespace }}"
    key: "value"
  register: csm_public_key
  run_once: true
  delegate_to: localhost

# Write the public half of the keypair as well
- name: Create the CSM public key file on target hosts
  lineinfile:
    create: true
    line: "{{ csm_public_key['response'] }}"
    path: /root/.ssh/csm-ecdsa.pub
    state: present
    mode: '644'
