# Please refer to https://github.com/Cray-HPE/base-charts/blob/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  type: Deployment
  nameOverride: "csm-ssh-keys"
  fullnameOverride: "csm-ssh-keys"
  serviceAccountName: "csmsshkeys"
  replicaCount: 1
  containers:
    cfs-trust:
      name: "csm-ssh-keys"
      image:
        repository: "cray/csm-ssh-keys"
        pullPolicy: Always
  service:
    enabled: false
csm-ssh-keys:
  name: "csm-ssh-keys"
  namespace: services
  image_version: "latest"
