# Copyright 2020 Hewlett Packard Enterprise Development LP

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "csmsshkeys"
  labels:
    app.kubernetes.io/name: "csmsshkeys"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - update
  - get
  - put
  - list
  - patch